Repository Chd3451/learning-next, pull requests merged in 2023-11, with the labels that each got.

#1 feature/add-styling
  .env.example
  .eslintrc.json
  .gitignore
  .nvmrc
  README.md
  app/layout.tsx
  app/lib/data.ts
  app/lib/definitions.ts
  app/lib/placeholder-data.js
  app/lib/utils.ts
  app/page.tsx
  app/ui/acme-logo.tsx
  app/ui/button.tsx
  app/ui/customers/table.tsx
  app/ui/dashboard/cards.tsx
  app/ui/dashboard/latest-invoices.tsx
  app/ui/dashboard/nav-links.tsx
  app/ui/dashboard/revenue-chart.tsx
  app/ui/dashboard/sidenav.tsx
  app/ui/global.css
  app/ui/home.module.css
  app/ui/invoices/breadcrumbs.tsx
  app/ui/invoices/buttons.tsx
  app/ui/invoices/create-form.tsx
  app/ui/invoices/edit-form.tsx
  app/ui/invoices/pagination.tsx
  app/ui/invoices/status.tsx
  app/ui/invoices/table.tsx
  app/ui/login-form.tsx
  app/ui/search.tsx
  app/ui/skeletons.tsx
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  public/customers/amy-burns.png
  public/customers/balazs-orban.png
  public/customers/delba-de-oliveira.png
  public/customers/emil-kowalski.png
  public/customers/evil-rabbit.png
  public/customers/guillermo-rauch.png
  public/customers/hector-simpson.png
  public/customers/jared-palmer.png
  public/customers/lee-robinson.png
  public/customers/michael-novotny.png
  public/customers/steph-dietz.png
  public/customers/steven-tey.png
  public/favicon.ico
  public/hero-desktop.png
  public/hero-mobile.png
  public/opengraph-image.png
  scripts/seed.js
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#2 feature/add-optimized-images-and-fonts
  README.md
  app/layout.tsx
  app/page.tsx
  app/ui/fonts.ts
Labels: enhancement

#3 feature/layouts-and-pages
  app/dashboard/customers/page.tsx
  app/dashboard/invoices/page.tsx
  app/dashboard/layout.tsx
  app/dashboard/page.tsx
  package-lock.json
  package.json
Labels: enhancement

#4 feat: linking pages and setting client-side navigation
  app/ui/dashboard/nav-links.tsx
Labels: enhancement

#5 develop: mergin develop to deploy vercel
  .env.example
  .eslintrc.json
  .gitignore
  .nvmrc
  README.md
  app/dashboard/customers/page.tsx
  app/dashboard/invoices/page.tsx
  app/dashboard/layout.tsx
  app/dashboard/page.tsx
  app/layout.tsx
  app/lib/data.ts
  app/lib/definitions.ts
  app/lib/placeholder-data.js
  app/lib/utils.ts
  app/page.tsx
  app/ui/acme-logo.tsx
  app/ui/button.tsx
  app/ui/customers/table.tsx
  app/ui/dashboard/cards.tsx
  app/ui/dashboard/latest-invoices.tsx
  app/ui/dashboard/nav-links.tsx
  app/ui/dashboard/revenue-chart.tsx
  app/ui/dashboard/sidenav.tsx
  app/ui/fonts.ts
  app/ui/global.css
  app/ui/home.module.css
  app/ui/invoices/breadcrumbs.tsx
  app/ui/invoices/buttons.tsx
  app/ui/invoices/create-form.tsx
  app/ui/invoices/edit-form.tsx
  app/ui/invoices/pagination.tsx
  app/ui/invoices/status.tsx
  app/ui/invoices/table.tsx
  app/ui/login-form.tsx
  app/ui/search.tsx
  app/ui/skeletons.tsx
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  public/customers/amy-burns.png
  public/customers/balazs-orban.png
  public/customers/delba-de-oliveira.png
  public/customers/emil-kowalski.png
  public/customers/evil-rabbit.png
  public/customers/guillermo-rauch.png
  public/customers/hector-simpson.png
  public/customers/jared-palmer.png
  public/customers/lee-robinson.png
  public/customers/michael-novotny.png
  public/customers/steph-dietz.png
  public/customers/steven-tey.png
  public/favicon.ico
  public/hero-desktop.png
  public/hero-mobile.png
  public/opengraph-image.png
  scripts/seed.js
  tailwind.config.ts
  tsconfig.json
Labels: enhancement, help wanted

#17 feature/add streaming
  app/dashboard/(overview)/loading.tsx
  app/dashboard/(overview)/page.tsx
  app/dashboard/page.tsx
  app/ui/dashboard/cards.tsx
  app/ui/dashboard/latest-invoices.tsx
  app/ui/dashboard/revenue-chart.tsx
Labels: enhancement

#21 fix/hook-search-bug/GI-20
  app/ui/search.tsx
Labels: bug
